"""CSV export of any table the tool displays.

Every export carries its provenance header: when it was generated, from which database, at which
day-index cutoff, and the data-quality figures for the campaigns involved. A CSV that circulates
without those is a CSV that gets quoted without them.
"""

from __future__ import annotations

import csv
import io
import sqlite3
from typing import Any

from ..actor import actor, now_utc
from ..db import query

# Imported from the submodule, not the package: cib.metrics re-exports compare() as a
# function, which shadows the module of the same name.
from ..metrics.compare import METRIC_ORDER, compare


def _writer() -> tuple[io.StringIO, Any]:
    buffer = io.StringIO()
    return buffer, csv.writer(buffer, lineterminator="\n")


def _provenance_rows(title: str, extra: list[list[str]] | None = None) -> list[list[str]]:
    rows = [
        [f"# {title}"],
        [f"# Generated at (UTC): {now_utc()}"],
        [f"# Generated by: {actor()}"],
        ["# Every figure below is traceable to article, mention or escalation rows in the "
         "source database."],
    ]
    rows.extend(extra or [])
    rows.append([])
    return rows


def _fmt(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, dict):
        return "; ".join(f"{k}={v}" for k, v in value.items())
    return str(value)


def comparison_csv(conn: sqlite3.Connection, campaign_refs: list[str | int],
                   at_day_index: int | None = None) -> str:
    """The comparison table — the measured format that replaces low/medium/high ratings."""
    result = compare(conn, campaign_refs, at_day_index)
    buffer, writer = _writer()
    slugs = [c["campaign_slug"] for c in result["campaigns"]]

    for row in _provenance_rows("Campaign comparison", [
        [f"# Day-index cutoff: {result['at_day_index']} "
         f"({'explicit' if result['cutoff_was_explicit'] else 'derived'})"],
        [f"# Campaigns: {', '.join(slugs) or '(none with a publication date)'}"],
    ]):
        writer.writerow(row)

    writer.writerow(["Metric", "Unit", *slugs, "Definition"])
    for key in METRIC_ORDER:
        cells = []
        for column in result["campaigns"]:
            metric = column["metrics"].get(key)
            if metric is None:
                cells.append("")
            elif not metric["available"]:
                cells.append(f"not available — {metric['unavailable_reason']}")
            else:
                cells.append(_fmt(metric["value"]))
        sample = next((c["metrics"][key] for c in result["campaigns"] if key in c["metrics"]), None)
        if sample is None:
            continue
        writer.writerow([sample["label"], sample["unit"], *cells, sample["definition"]["plain"]])

    writer.writerow([])
    writer.writerow(["# Data quality"])
    writer.writerow(["Measure", *slugs])
    quality_keys = [
        ("articles_in_window", "Articles in window"),
        ("articles_total_imported", "Articles imported in total"),
        ("articles_undated", "Articles that could not be dated"),
        ("articles_missing_country_pct", "% articles with no country"),
        ("articles_with_body_text_pct", "% articles with body text"),
        ("outlets_missing_reach_pct", "% outlets with no sourced reach"),
        ("last_import_at", "Last import"),
    ]
    for key, label in quality_keys:
        writer.writerow([label, *[_fmt(c["data_quality"].get(key)) for c in result["campaigns"]]])

    if result["caveats"]:
        writer.writerow([])
        writer.writerow(["# Caveats — these must travel with the figures above"])
        for caveat in result["caveats"]:
            writer.writerow([caveat])

    if result["pre_publication"]:
        writer.writerow([])
        writer.writerow(["# Pre-publication campaigns, excluded from the table above by design"])
        for view in result["pre_publication"]:
            writer.writerow([view["campaign"]["slug"], view["footprint_refusal"]])

    return buffer.getvalue()


def articles_csv(conn: sqlite3.Connection, campaign_id: int,
                 article_ids: list[int] | None = None) -> str:
    """The evidence appendix: the article rows behind a figure, with import provenance."""
    if article_ids:
        placeholders = ",".join("?" * len(article_ids))
        rows = query(conn, f"""
            SELECT a.id, a.day_index, a.published_at, a.headline, a.url, a.byline,
                   a.country, a.language, a.is_original, a.cluster_id, a.word_count,
                   o.name AS outlet, o.domain, o.tier, o.reach_value, o.reach_source,
                   o.reach_is_estimated,
                   i.source AS import_source, i.file_name, i.imported_at, i.id AS import_id
              FROM articles a
              JOIN outlets o ON o.id = a.outlet_id
              JOIN imports i ON i.id = a.import_id
             WHERE a.campaign_id = ? AND a.id IN ({placeholders})
             ORDER BY a.published_at, a.id
        """, (campaign_id, *article_ids))
    else:
        rows = query(conn, """
            SELECT a.id, a.day_index, a.published_at, a.headline, a.url, a.byline,
                   a.country, a.language, a.is_original, a.cluster_id, a.word_count,
                   o.name AS outlet, o.domain, o.tier, o.reach_value, o.reach_source,
                   o.reach_is_estimated,
                   i.source AS import_source, i.file_name, i.imported_at, i.id AS import_id
              FROM articles a
              JOIN outlets o ON o.id = a.outlet_id
              JOIN imports i ON i.id = a.import_id
             WHERE a.campaign_id = ?
             ORDER BY a.published_at, a.id
        """, (campaign_id,))

    buffer, writer = _writer()
    for row in _provenance_rows("Article evidence"):
        writer.writerow(row)
    if not rows:
        writer.writerow(["(no articles)"])
        return buffer.getvalue()
    writer.writerow(list(rows[0].keys()))
    for row in rows:
        writer.writerow([_fmt(v) for v in tuple(row)])
    return buffer.getvalue()


def escalations_csv(conn: sqlite3.Connection, campaign_id: int) -> str:
    rows = query(conn, """
        SELECT id, occurred_at, escalation_type, actor_name, actor_type, severity,
               description, source_url, verified_by, verified_at, created_by, created_at
          FROM escalations WHERE campaign_id = ? ORDER BY occurred_at
    """, (campaign_id,))
    buffer, writer = _writer()
    for row in _provenance_rows("Escalation log"):
        writer.writerow(row)
    if not rows:
        writer.writerow(["(no escalations logged)"])
        return buffer.getvalue()
    writer.writerow(list(rows[0].keys()))
    for row in rows:
        writer.writerow([_fmt(v) for v in tuple(row)])
    return buffer.getvalue()


def mentions_csv(conn: sqlite3.Connection, campaign_id: int,
                 mention_ids: list[int] | None = None) -> str:
    where = "a.campaign_id = ?"
    params: tuple = (campaign_id,)
    if mention_ids:
        where += f" AND m.id IN ({','.join('?' * len(mention_ids))})"
        params = (campaign_id, *mention_ids)
    rows = query(conn, f"""
        SELECT m.id, e.name AS entity, e.type AS entity_type, m.role, m.confidence,
               m.classified_by, m.evidence_sentence, a.id AS article_id, a.day_index,
               a.published_at, a.headline, a.url, o.name AS outlet
          FROM mentions m
          JOIN entities e ON e.id = m.entity_id
          JOIN articles a ON a.id = m.article_id
          JOIN outlets o ON o.id = a.outlet_id
         WHERE {where}
         ORDER BY a.day_index, m.id
    """, params)
    buffer, writer = _writer()
    for row in _provenance_rows("Entity mentions"):
        writer.writerow(row)
    if not rows:
        writer.writerow(["(no mentions)"])
        return buffer.getvalue()
    writer.writerow(list(rows[0].keys()))
    for row in rows:
        writer.writerow([_fmt(v) for v in tuple(row)])
    return buffer.getvalue()
