"""Exports: the briefing has to be defensible line by line, so that is what is tested."""

from __future__ import annotations

import pytest

from cib.export import briefing, tables
from cib.repo import campaigns as campaign_repo
from cib.repo import events as event_repo


@pytest.fixture
def with_escalations(conn, loaded):
    event_repo.add_escalation(
        conn, campaign_id=loaded, occurred_at="2019-03-08T00:00:00",
        escalation_type="certifier_response", actor_name="Example Certification Body",
        description="Opened a review of its fishmeal sourcing standard.",
        source_url="https://certifier.example/statement", severity=3,
    )
    escalation_id = event_repo.add_escalation(
        conn, campaign_id=loaded, occurred_at="2019-03-20T00:00:00",
        escalation_type="regulatory_action", actor_name="Example Food Authority",
        description="Opened an inquiry into imports.",
        source_url="https://authority.example/inquiry", severity=4,
    )
    event_repo.verify_escalation(conn, escalation_id, "test:analyst")
    return loaded


def test_comparison_csv_carries_provenance_and_definitions(conn, loaded, sample_csv):
    from cib import dedup
    from cib.ingest import csv_generic

    other = campaign_repo.create(
        conn, name="Second campaign", publisher_org="P", campaign_type="coalition",
        status="archived", published_at="2019-03-04T00:00:00",
    )
    csv_generic.import_file(conn, campaign_ref=other, path=sample_csv)
    dedup.cluster_campaign(conn, other)

    output = tables.comparison_csv(conn, [loaded, other], at_day_index=5)
    assert "# Generated at (UTC):" in output
    assert "# Generated by:" in output
    assert "# Day-index cutoff: 5" in output
    assert "# Data quality" in output
    assert "Unique stories" in output and "Unique outlets" in output
    # The definition column is what makes a circulated CSV arguable.
    assert "after collapsing syndicated republications" in output


def test_article_csv_carries_import_provenance(conn, loaded):
    output = tables.articles_csv(conn, loaded)
    assert "import_source" in output and "imported_at" in output and "file_name" in output
    assert "syndication_sample.csv" in output


def test_escalation_csv_includes_source_urls(with_escalations, conn):
    output = tables.escalations_csv(conn, with_escalations)
    assert "https://certifier.example/statement" in output
    assert "https://authority.example/inquiry" in output


def test_briefing_states_every_figure_with_its_source_row_count(with_escalations, conn):
    data = briefing.build(conn, [with_escalations])
    markdown = briefing.to_markdown(data)

    assert "| Metric | Value | Source rows | What it counts |" in markdown
    assert "Unique stories" in markdown
    assert "Evidence appendix" in markdown
    assert "syndication_sample.csv" in markdown
    assert "Data quality" in markdown
    # Severity anchors have to be printed, or a weighted total cannot be defended.
    assert "Binding regulatory or customs measure" in markdown


def test_briefing_prints_the_severity_scale_next_to_the_escalations(with_escalations, conn):
    markdown = briefing.to_markdown(briefing.build(conn, [with_escalations]))
    assert "Severity scale:" in markdown
    assert "Example Food Authority" in markdown
    assert "https://authority.example/inquiry" in markdown


def test_briefing_says_so_when_the_escalation_log_is_empty(loaded, conn):
    markdown = briefing.to_markdown(briefing.build(conn, [loaded]))
    assert "an empty log means nothing has been recorded, not that nothing has happened" in markdown


def test_briefing_for_a_pre_publication_campaign_refuses_a_footprint(conn, loaded):
    campaign_id = campaign_repo.create(
        conn, name="Forthcoming", publisher_org="Test Publisher",
        campaign_type="journalism", status="pre_publication", published_at=None,
    )
    campaign_repo.add_precedent(conn, campaign_id, loaded, rationale="Same publisher.")
    event_repo.add_inbound_signal(
        conn, campaign_id=campaign_id, occurred_at="2019-02-10T00:00:00",
        channel="tender", summary="Tender questionnaire asked about fishmeal origin.",
    )

    markdown = briefing.to_markdown(briefing.build(conn, [campaign_id]))
    assert "This campaign has not published" in markdown
    assert "Publisher precedent" in markdown
    assert "Tender questionnaire" in markdown
    assert "Measured footprint" not in markdown


def test_briefing_html_is_self_contained(with_escalations, conn):
    html = briefing.to_html(briefing.build(conn, [with_escalations]))
    assert html.startswith("<!doctype html>")
    assert "<style>" in html
    # No external requests: a briefing has to render on a laptop with no network.
    assert "http://" not in html.split("<body>")[0]
    assert "src=" not in html


def test_briefing_evidence_is_capped_and_says_so(with_escalations, conn):
    data = briefing.build(conn, [with_escalations])
    assert data["evidence_shown"] <= briefing.EVIDENCE_LIMIT
    assert data["evidence_total"] == 12
    markdown = briefing.to_markdown(data)
    assert f"Showing {data['evidence_shown']} of 12 article rows" in markdown
