#!/usr/bin/env python3
"""Regenerate docs/METRICS.md from the metric definitions.

The definitions live in one place — backend/cib/metrics/definitions.py — because they will be
argued about more than the code will. This renders them to Markdown so the documentation cannot
drift from what the engine actually computes; `test_docs.py` fails if the checked-in file is stale.

Usage:  python scripts/render_metrics_doc.py [--check]
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from cib.metrics import METRIC_ORDER  # noqa: E402
from cib.metrics import definitions as metric_definitions  # noqa: E402
from cib.models import ROLE_WEIGHTS, SEVERITY_ANCHORS  # noqa: E402

TARGET = ROOT / "docs" / "METRICS.md"

GROUPS = [
    ("Footprint — how much coverage, and how far it travelled", [
        "unique_stories", "unique_outlets", "total_articles", "syndication_ratio",
        "tier_mix", "country_count", "language_count", "total_reach", "reach_coverage",
    ]),
    ("Velocity and persistence — how fast it escalated, how long it lasted", [
        "peak_day", "peak_volume", "days_to_peak", "half_life_days",
        "days_to_90pct", "long_tail",
    ]),
    ("Company exposure — how centrally we appear, and against whom", [
        "own_company_mentions", "depth_score", "first_mention_day", "competitor_comparison",
    ]),
    ("Escalation — what the coverage actually caused", [
        "escalation_count", "days_to_first_escalation", "severity_weighted_total",
        "escalation_chain",
    ]),
]


def render() -> str:
    lines = [
        "# Metric definitions",
        "",
        "<!-- Generated by scripts/render_metrics_doc.py from backend/cib/metrics/definitions.py.",
        "     Do not edit by hand: edit the definitions and re-run `make docs`. -->",
        "",
        "Every metric the tool computes, in plain language, with exactly which rows it counts and",
        "what it cannot tell you. These definitions are attached to every value the engine returns,",
        "rendered in the dashboard, and printed in the briefing export — so the wording here is the",
        "wording everywhere.",
        "",
        "A metric with no definition in `definitions.py` fails the test suite and cannot ship.",
        "",
    ]

    covered = {key for _, keys in GROUPS for key in keys}
    missing = [k for k in METRIC_ORDER if k not in covered]
    for title, keys in [*GROUPS, *([("Other", missing)] if missing else [])]:
        lines += [f"## {title}", ""]
        for key in keys:
            d = metric_definitions.DEFINITIONS[key]
            lines += [
                f"### {d.label}",
                "",
                f"`{d.key}` · measured in {d.unit}",
                "",
                d.plain,
                "",
                f"**Counts:** {d.counts}",
                "",
            ]
            if d.caveat:
                lines += [f"**Caveat:** {d.caveat}", ""]

    lines += [
        "## Exposure depth weights",
        "",
        "Being the subject of a story is not the same as being listed in passing, so mentions are",
        "weighted by the role the article gives the company:",
        "",
        "| Role | Weight |",
        "|---|---|",
    ]
    lines += [f"| {role.replace('_', ' ')} | ×{weight} |" for role, weight in ROLE_WEIGHTS.items()]
    lines += [
        "",
        "The weighted total is never returned without these components. \"We scored 34\" is exactly",
        "the kind of number this tool exists to replace.",
        "",
        "## Escalation severity anchors",
        "",
        "A severity-weighted total is only defensible if the scale is written down:",
        "",
        "| Severity | Meaning |",
        "|---|---|",
    ]
    lines += [f"| {value} | {anchor} |" for value, anchor in SEVERITY_ANCHORS.items()]
    lines += [
        "",
        "## Day index",
        "",
        "`day_index` is what makes campaigns comparable: whole days from the campaign's publication",
        "date, measured on calendar dates in the campaign's own timezone.",
        "",
        "- **Day 0 is the publication date itself**, not the day after.",
        "- **`day_index` can be negative.** Embargo breaks and pre-publication leaks are real",
        "  coverage; clamping them to zero would hide exactly the thing worth noticing.",
        "- Articles whose date cannot be parsed have a null `day_index`. They are **excluded** from",
        "  every day-truncated figure and reported separately as a data-quality number, never",
        "  folded silently into day 0.",
        "",
        "## What is deliberately not a metric",
        "",
        "**Sentiment.** Coverage about labour or environmental abuse is negative by construction, so",
        "a tone score does not discriminate between a trade story and a crisis. Tone can be stored",
        "as a secondary label in the `article_tone` table, always with the sentence supporting it,",
        "but no metric function reads that table and no comparison endpoint exposes it. A test",
        "asserts this.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET} is out of date. Run: make docs", file=sys.stderr)
            return 1
        print(f"{TARGET} is up to date.")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
